import { cp, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { articles } from "../content/articles.mjs";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const out = join(root, "dist");
const repo = "uk-transport-manager-cpc-prep-web";
const origin = `https://mcyj.github.io/${repo}`;
const base = `/${repo}`;
const checkedAt = "2026-09-18";
const officialSpec = "https://cms.ciltuk.org.uk/media/btqlnrxl/ao-qua-0624-cilt-uk-cpc-road-haulage-specification-v42.pdf";
const officialResources = "https://ciltuk.org.uk/organisations/awarding-organisation/learning-partner-resources/";
const supportEmail = "june1012june@gmail.com";

const escapeHtml = (value) => String(value)
  .replaceAll("&", "&amp;")
  .replaceAll("<", "&lt;")
  .replaceAll(">", "&gt;")
  .replaceAll('"', "&quot;");

async function put(path, contents) {
  const target = join(out, path);
  await mkdir(dirname(target), { recursive: true });
  await writeFile(target, contents);
}

function nav() {
  return `<header class="site-header"><a class="brand" href="${base}/en/"><img src="${base}/assets/app-icon.png" width="42" height="42" alt=""><span>UK Transport Manager<br><strong>CPC Prep</strong></span></a><nav aria-label="Primary"><a href="${base}/en/guides/">Study guides</a><a href="${base}/en/faq/">FAQ</a><a href="${base}/en/support/">Support</a></nav></header>`;
}

function footer() {
  return `<footer><div><strong>UK Transport Manager CPC Prep</strong><p>Independent study support from RushLabs. Not affiliated with or endorsed by CILT(UK).</p></div><nav aria-label="Legal"><a href="${base}/en/privacy/">Privacy</a><a href="${base}/en/terms/">Terms</a><a href="${base}/en/support/">Support</a><a href="${base}/en/contact/">Contact</a></nav><p class="source-note">Official qualification details checked ${checkedAt}. Always confirm current rules with CILT(UK).</p></footer>`;
}

function layout({ title, description, path, body, type = "website", jsonLd = null }) {
  const canonical = `${origin}${path}`;
  const schema = jsonLd ? `<script type="application/ld+json">${JSON.stringify(jsonLd).replaceAll("<", "\\u003c")}</script>` : "";
  return `<!doctype html><html lang="en-GB"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escapeHtml(title)}</title><meta name="description" content="${escapeHtml(description)}"><link rel="canonical" href="${canonical}"><link rel="alternate" hreflang="en-GB" href="${canonical}"><link rel="alternate" hreflang="x-default" href="${canonical}"><meta property="og:type" content="${type}"><meta property="og:title" content="${escapeHtml(title)}"><meta property="og:description" content="${escapeHtml(description)}"><meta property="og:url" content="${canonical}"><meta property="og:site_name" content="UK Transport Manager CPC Prep"><meta name="twitter:card" content="summary"><meta name="theme-color" content="#0b1830"><link rel="icon" href="${base}/assets/app-icon.png"><link rel="stylesheet" href="${base}/assets/styles.css">${schema}</head><body><a class="skip" href="#main">Skip to content</a><div class="page-shell">${nav()}<main id="main">${body}</main>${footer()}</div></body></html>`;
}

function comingSoonButtons(label = "Get the app") {
  return `<div class="store-block" aria-labelledby="store-heading"><p class="eyebrow" id="store-heading">${label}</p><div class="store-row"><span class="store-button disabled" aria-label="Apple App Store coming soon"><span aria-hidden="true">●</span><span><small>App Store</small>Coming soon</span></span><span class="store-button disabled" aria-label="Google Play coming soon"><span aria-hidden="true">▶</span><span><small>Google Play</small>Coming soon</span></span></div><p class="store-note">Both versions are under Store review. Availability is not yet confirmed.</p></div>`;
}

const homeBody = `
  <section class="hero">
    <div class="hero-copy"><p class="eyebrow">Road Haulage · CILT(UK) Level 3</p><h1>Build the knowledge.<br><span>Practise the decisions.</span></h1><p class="lede">Focused multiple-choice practice, case-study reasoning and local-first revision for the UK Transport Manager CPC Road Haulage qualification.</p>${comingSoonButtons()}</div>
    <div class="phone-stage" aria-label="App practice question preview"><img src="${base}/assets/screenshots/question.png" width="1080" height="1920" alt="UK Transport Manager CPC Prep showing a financial ratio practice question"></div>
  </section>
  <section class="proof-strip" aria-label="App highlights"><div><strong>40</strong><span>reviewed multiple-choice questions</span></div><div><strong>72</strong><span>case-study scenarios across 24 sets</span></div><div><strong>Offline</strong><span>bundled learning and local progress</span></div></section>
  <section class="split section"><div><p class="eyebrow">Two papers, two skills</p><h2>Recall accurately. Apply clearly.</h2><p>Paper 1 rewards reliable closed-book knowledge. Paper 2 asks you to apply it to three open-book case studies. The app separates those modes so practice has a clear purpose.</p><a class="text-link" href="${base}/en/guides/qualification-guide/">Read the qualification guide <span aria-hidden="true">→</span></a></div><div class="exam-card"><div><span>Paper 1</span><strong>40 questions · 120 min</strong><p>Closed book · pass mark 28/40</p></div><div><span>Paper 2</span><strong>3 case studies · 135 min</strong><p>Open book · pass mark 30/60</p></div><p class="source-note">Both papers must be passed independently. Source: CILT(UK) qualification specification v4.2.</p></div></section>
  <section class="section"><div class="section-heading"><div><p class="eyebrow">Inside the app</p><h2>Practice that shows its working</h2></div><p>Answer, check the reasoning, and move through the reviewed release set without needing an account.</p></div><div class="screens"><figure><img loading="lazy" src="${base}/assets/screenshots/question.png" width="1080" height="1920" alt="An unanswered current-ratio practice question"><figcaption>Read the question and choose deliberately.</figcaption></figure><figure><img loading="lazy" src="${base}/assets/screenshots/explanation.png" width="1080" height="1920" alt="Answer review showing the correct ratio and explanation"><figcaption>Review the correct answer and explanation.</figcaption></figure><figure><img loading="lazy" src="${base}/assets/screenshots/progress.png" width="1080" height="1920" alt="The next practice question with progress at 10 of 40"><figcaption>Continue through a focused reviewed set.</figcaption></figure></div></section>
  <section class="section guide-preview"><div class="section-heading"><div><p class="eyebrow">Free study guides</p><h2>Start with the exam, not the app</h2></div><a class="text-link" href="${base}/en/guides/">Browse all 12 guides <span aria-hidden="true">→</span></a></div><div class="guide-grid">${articles.slice(0, 6).map((a, i) => `<a class="guide-card" href="${base}/en/guides/${a.slug}/"><span>${String(i + 1).padStart(2, "0")} · ${a.category}</span><h3>${a.title}</h3><p>${a.description}</p></a>`).join("")}</div></section>
  <section class="section faq-teaser"><div><p class="eyebrow">Independent study aid</p><h2>Clear about what it is—and what it is not.</h2></div><div><p>The app does not reproduce official papers, promise a pass or replace current instructions from CILT(UK) and your approved learning partner.</p><a class="text-link" href="${base}/en/faq/">Read the FAQ <span aria-hidden="true">→</span></a></div></section>
  <section class="final-cta"><h2>Turn reading into retrieval.</h2><p>UK Transport Manager CPC Prep is currently under Store review.</p>${comingSoonButtons("App availability")}</section>`;

const softwareSchema = { "@context": "https://schema.org", "@type": "SoftwareApplication", name: "UK Transport Manager CPC Prep", applicationCategory: "EducationalApplication", operatingSystem: "Android, iOS", description: "Independent Road Haulage Transport Manager CPC practice and revision app.", publisher: { "@type": "Organization", name: "RushLabs" } };

const guideCards = articles.map((a) => `<a class="guide-card" href="${base}/en/guides/${a.slug}/"><span>${a.category}</span><h2>${a.title}</h2><p>${a.description}</p></a>`).join("");
const guidesBody = `<section class="page-intro"><p class="eyebrow">Study library</p><h1>Road Haulage CPC guides</h1><p>Practical, original guidance grounded in the March 2026 CILT(UK) qualification specification. Current assessment dates and booking details remain with CILT(UK) and approved learning partners.</p></section><section class="guide-grid all-guides">${guideCards}</section><aside class="official-source"><h2>Official information first</h2><p>Use these guides for preparation methods. Use the awarding organisation for the current specification, timetable and assessment instructions.</p><div><a href="${officialSpec}">Qualification specification (PDF)</a><a href="${officialResources}">Timetables and sample papers</a></div></aside>`;

function articlePage(article) {
  const related = article.related.map((slug) => articles.find((item) => item.slug === slug)).filter(Boolean);
  const body = `<article class="article"><nav class="breadcrumbs" aria-label="Breadcrumb"><a href="${base}/en/">Home</a><span>/</span><a href="${base}/en/guides/">Guides</a><span>/</span><span aria-current="page">${article.category}</span></nav><header><p class="eyebrow">${article.category}</p><h1>${article.title}</h1><p class="lede">${article.description}</p><p class="article-meta">Reviewed against official sources · ${checkedAt}</p></header><div class="article-layout"><div class="article-copy">${article.body}<section class="sources"><h2>Official sources</h2><ul><li><a href="${officialSpec}">CILT(UK) Road Haulage Qualification Specification v4.2</a></li><li><a href="${officialResources}">CILT(UK) Learning Partner Resources</a></li></ul><p>Confirm current dates, fees, booking arrangements and permitted materials with CILT(UK) or your approved learning partner.</p></section></div><aside class="article-aside"><img src="${base}/assets/app-icon.png" width="88" height="88" alt="UK Transport Manager CPC Prep icon"><h2>Practise the reasoning</h2><p>Use focused questions, case-study scenarios and local progress tracking in the app.</p><p class="status-pill">Store review in progress</p></aside></div><section class="related"><p class="eyebrow">Continue studying</p><div class="guide-grid">${related.map((item) => `<a class="guide-card" href="${base}/en/guides/${item.slug}/"><span>${item.category}</span><h3>${item.title}</h3></a>`).join("")}</div></section></article>`;
  const schema = { "@context": "https://schema.org", "@type": "Article", headline: article.title, description: article.description, datePublished: "2026-09-18", dateModified: "2026-09-18", inLanguage: "en-GB", author: { "@type": "Organization", name: "RushLabs" }, publisher: { "@type": "Organization", name: "RushLabs" }, mainEntityOfPage: `${origin}/en/guides/${article.slug}/` };
  return layout({ title: `${article.title} | UK Transport Manager CPC Prep`, description: article.description, path: `/en/guides/${article.slug}/`, type: "article", body, jsonLd: schema });
}

const faqItems = [
  ["Is this an official CILT(UK) app?", "No. It is independently produced by RushLabs and is not affiliated with, endorsed by or an official product of CILT(UK), the Department for Transport or the Driver and Vehicle Standards Agency."],
  ["Does the app reproduce official examination papers?", "No. It contains original practice questions and scenarios. Use CILT(UK)'s official resources for the current specification and authorised sample material."],
  ["What does the app include?", "The submitted release contains 40 reviewed multiple-choice practice questions with explanations, 24 case-study sets containing 72 scenarios, focused concepts and terminology, saved questions, progress tracking and offline bundled learning material."],
  ["Does a practice score guarantee a pass?", "No. Practice results do not guarantee an examination pass, professional competence or legal compliance."],
  ["Do I need an account?", "No RushLabs account or sign-in is required in the current app."],
  ["Where is my learning progress stored?", "Practice answers, notes, bookmarks and progress are stored locally in the app's private storage on your device. See the Privacy Policy for details."],
  ["When will the app be available?", "The Android and iOS versions have been submitted for Store review. Approval and public availability are not yet confirmed, so no launch date is promised."],
  ["Where can I find current assessment dates?", "Use CILT(UK)'s Learning Partner Resources page and confirm arrangements with your approved learning partner."],
];
const faqBody = `<section class="page-intro"><p class="eyebrow">Questions & answers</p><h1>What to know before you study</h1><p>Clear answers about the qualification, the app and its current availability.</p></section><section class="faq-list">${faqItems.map(([q, a]) => `<details><summary>${q}</summary><p>${a}</p></details>`).join("")}</section>`;
const faqSchema = { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: faqItems.map(([name, text]) => ({ "@type": "Question", name, acceptedAnswer: { "@type": "Answer", text } })) };

const privacyBody = `<article class="policy"><p class="eyebrow">Legal</p><h1>Privacy Policy</h1><p class="article-meta">Effective: 18 September 2026</p><h2>Who operates the app</h2><p>RushLabs operates UK Transport Manager CPC Prep (GLB-0668). Privacy questions can be sent to <a href="mailto:${supportEmail}">${supportEmail}</a>.</p><h2>Learning information on your device</h2><p>The app stores practice answers, case-study working, notes, bookmarks, progress, concept completion, term-memory records, study time and learning preferences in app-private storage. The current app does not require a RushLabs account or send those learning records to a RushLabs server. No advertising or analytics service is integrated in the current implementation.</p><h2>Purchases</h2><p>Apple App Store or Google Play handles purchases and payment information under its own policies. The app uses store product, transaction and subscription information to display purchase options, process purchase or restoration events and determine access. RushLabs does not receive card details through the app.</p><h2>Backups you choose to copy</h2><p>The app can display a text backup for you to copy and restore text you paste. It may contain answers, notes and learning settings, but excludes subscription and payment data. Protect copied backups and review the privacy practices of any destination you choose.</p><h2>Retention and deletion</h2><p>Learning records remain on your device until replaced through normal use or removed with the app's data. To remove app-private records, use your device's app-data controls or delete the app and its data. Offloading may retain data. Deleting the app does not cancel a Store subscription.</p><h2>Support messages</h2><p>If you contact support, RushLabs receives the message and information you voluntarily include. Do not send passwords, payment details, purchase tokens or private backup contents. Support correspondence is used to respond and retained only as needed for support and applicable obligations.</p><h2>This website</h2><p>This static website does not use analytics, advertising cookies, accounts or contact forms. Following external links is subject to the destination's privacy practices.</p></article>`;
const termsBody = `<article class="policy"><p class="eyebrow">Legal</p><h1>Terms of Use</h1><p class="article-meta">Effective: 18 September 2026</p><h2>Independent learning service</h2><p>The app is an independent study aid for Transport Manager CPC preparation. It is not an official exam, qualification or certification service and does not claim endorsement by an examination authority. Practice results do not guarantee an examination pass, professional competence or legal compliance.</p><h2>Content and personal use</h2><p>Use the app and its original learning material for personal study. Do not redistribute protected material or use the app unlawfully. Keep an independent backup if you need your notes and answers; deleting the app or its data can remove local records.</p><h2>Store purchases</h2><p>The app may offer monthly or yearly Premium subscriptions. Purchase only on the basis of the product name, duration, enabled features and full localised price displayed in the Store-backed purchase screen. Manage renewals, cancellation and refund requests through the Store account that purchased the subscription. Deleting the app does not cancel a subscription.</p><h2>Current official information</h2><p>Consult the current CILT(UK) specification, timetable, assessment instructions and applicable official guidance for authoritative requirements. Website guides are educational summaries and study methods, not administrative instructions.</p><h2>Support</h2><p>Contact <a href="mailto:${supportEmail}">${supportEmail}</a> for app support. These terms do not limit rights that cannot lawfully be excluded.</p></article>`;
const supportBody = `<section class="page-intro"><p class="eyebrow">App support</p><h1>Tell us what went wrong</h1><p>Include the app name, device OS, app version and a short description. Screenshots help when they contain no private information.</p><a class="primary-button" href="mailto:${supportEmail}?subject=UK%20Transport%20Manager%20CPC%20Prep%20support">Email RushLabs support</a></section><section class="support-grid"><div><h2>Keep private information private</h2><p>Do not send passwords, card information, purchase tokens, receipts or your full learning backup.</p></div><div><h2>Restore purchases</h2><p>Use the same purchasing Store account and the app's Restore purchases action where supported. Manage renewal, cancellation or refunds through Apple or Google.</p></div><div><h2>Examination questions</h2><p>Contact CILT(UK) or your approved learning partner about registration, permitted materials, official results and qualification decisions.</p></div></section>`;
const contactBody = `<section class="page-intro contact"><p class="eyebrow">Contact</p><h1>RushLabs</h1><p>For UK Transport Manager CPC Prep support, privacy questions or website corrections:</p><a class="contact-email" href="mailto:${supportEmail}">${supportEmail}</a><p class="source-note">Please do not email passwords, payment details, purchase tokens, receipts or private learning backups.</p></section>`;

await rm(out, { recursive: true, force: true });
await mkdir(out, { recursive: true });
await cp(join(root, "assets"), join(out, "assets"), { recursive: true });
await cp(join(root, ".nojekyll"), join(out, ".nojekyll"));
await cp(join(root, "assets", "app-icon.png"), join(out, "favicon.png"));
await cp(join(root, "styles.css"), join(out, "assets", "styles.css"));

await put("index.html", `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>UK Transport Manager CPC Prep</title><meta name="description" content="Road Haulage Transport Manager CPC practice and study guides."><meta http-equiv="refresh" content="0;url=./en/"><link rel="canonical" href="${origin}/en/"><script>location.replace('./en/')</script></head><body><main id="main"><p><a href="./en/">Continue to UK Transport Manager CPC Prep</a></p></main></body></html>`);
await put("en/index.html", layout({ title: "UK Transport Manager CPC Prep | Road Haulage exam practice", description: "Focused Road Haulage Transport Manager CPC practice, case-study reasoning and offline revision for the CILT(UK) Level 3 qualification.", path: "/en/", body: homeBody, jsonLd: softwareSchema }));
await put("en/guides/index.html", layout({ title: "Transport Manager CPC study guides", description: "Original study guides for Road Haulage Transport Manager CPC Paper 1, Paper 2, revision, calculations and exam preparation.", path: "/en/guides/", body: guidesBody }));
for (const article of articles) await put(`en/guides/${article.slug}/index.html`, articlePage(article));
await put("en/faq/index.html", layout({ title: "FAQ | UK Transport Manager CPC Prep", description: "Answers about UK Transport Manager CPC Prep, qualification sources, privacy, features and Store availability.", path: "/en/faq/", body: faqBody, jsonLd: faqSchema }));
await put("en/privacy/index.html", layout({ title: "Privacy Policy | UK Transport Manager CPC Prep", description: "Privacy information for the UK Transport Manager CPC Prep app and website.", path: "/en/privacy/", body: privacyBody }));
await put("en/terms/index.html", layout({ title: "Terms of Use | UK Transport Manager CPC Prep", description: "Terms for UK Transport Manager CPC Prep, its independent learning content and Store purchases.", path: "/en/terms/", body: termsBody }));
await put("en/support/index.html", layout({ title: "Support | UK Transport Manager CPC Prep", description: "Get help with UK Transport Manager CPC Prep, purchases, local learning records and app issues.", path: "/en/support/", body: supportBody }));
await put("en/contact/index.html", layout({ title: "Contact RushLabs | UK Transport Manager CPC Prep", description: "Contact RushLabs about UK Transport Manager CPC Prep support, privacy or website corrections.", path: "/en/contact/", body: contactBody }));
await put("404.html", layout({ title: "Page not found | UK Transport Manager CPC Prep", description: "The requested page could not be found.", path: "/404.html", body: `<section class="page-intro"><p class="eyebrow">404</p><h1>That page is not on this route.</h1><p>The study guides and app information are still available.</p><a class="primary-button" href="${base}/en/">Return home</a></section>` }));

const urls = ["/en/", "/en/guides/", ...articles.map((a) => `/en/guides/${a.slug}/`), "/en/faq/", "/en/privacy/", "/en/terms/", "/en/support/", "/en/contact/"];
await put("sitemap.xml", `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls.map((path) => `  <url><loc>${origin}${path}</loc><lastmod>${checkedAt}</lastmod></url>`).join("\n")}\n</urlset>\n`);
await put("robots.txt", `User-agent: *\nAllow: /\nSitemap: ${origin}/sitemap.xml\n`);

console.log(`Built ${urls.length} indexable pages in ${out}`);
